server:
  port: 10001
spring:
  application:
    name: u-context
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/uxue_cms?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto