server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
    gateway:
      routes:
        - id: cms-route
          uri: lb://u-context
          predicates:
            - Path=/context/**
          filters:
            - RewritePath=/(?<segment>.*),/$\{segment}
        - id: qms-route # 题目微服务路由
          uri: lb://u-question
          predicates:
            - Path=/question/**
          filters:
            - RewritePath=/(?<segment>.*),/$\{segment}
        - id: ums-route # 用户微服务路由
          uri: lb://u-member
          predicates:
            - Path=/member/**
          filters:
            - RewritePath=/(?<segment>.*),/$\{segment}
        - id: renrenfast-route # 人人后台服务路由
          uri: lb://renren-fast
          predicates:
            - Path=/renren-fast/**
          filters:
            - RewritePath=/renren-fast/(?<segment>.*),/renren-fast/$\{segment}
  application:
    name: gateway
