
server:
  port: 14000
spring:
  application:
    name: u-oss
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: myKey
      secret-key: mykey
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: offcn2021dzh

logging:
  level:
    com.offcn.oss: debug
