spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    #配置mybatis-plus日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #此为默认值，如果你的默认值和mp默认的一样,该配置可无
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
